version: "3.8"
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: famiyu-morita
      POSTGRES_PASSWORD: famiyu-morita
      POSTGRES_DB: famiyu-morita
    restart: always
    networks:
      - lesson
networks:
  lesson:
